{{- if .Values.applications.common.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-apps
  namespace: {{ .Values.argocd.namespace }}
spec:
  destination:
    namespace: {{ .Values.argocd.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      version: v3
      releaseName: start
      {{- with .Values.argocd.valueFiles }}
      valueFiles:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      parameters:
        - name: argocd.common.target_revision
          value: {{ .Values.argocd.common.target_revision }}
        {{- if .Values.helmParameters }}
        {{- include "template.helmParameters" (dict "prefix" "" "data" .Values.helmParameters) | indent 8 }}
        {{- end }}
    path: clusters/hub/_start/
    repoURL: https://github.com/smuda/demo-multi-cluster.git
    targetRevision: {{ .Values.argocd.common.target_revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}
