broker:
  globalnet: true
  namespace: "addon-submariner-broker"
  server: "cluster-1-control-plane:6443"

ipsec:
  psk: "8X" # Random value :-)

serviceAccounts:
  globalnet:
    create: true
  lighthouseAgent:
    create: true
  lighthouseCoreDns:
    create: true

submariner:
  cableDriver: libreswan
  globalCidr: "242.42.0.0/16"
  natEnabled: "false"
  serviceDiscovery: true

operator:
  image:
    pullPolicy: "IfNotPresent"
