{{- if .Values.root.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      version: v3
      releaseName: root
      {{- with .Values.argocd.valueFiles }}
      valueFiles:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      parameters:
        - name: argocd.common.target_revision
          value: {{ .Values.targetRevision }}
        {{- if .Values.helmParameters }}
        {{- include "template.helmParameters" (dict "prefix" "" "data" .Values.helmParameters) | indent 8 }}
        {{- end }}
    path: clusters/_start/
    repoURL: https://github.com/smuda/demo-multi-cluster.git
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
