apiVersion: v1
kind: Secret
metadata:
  name: cluster-2-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "cluster-2"
  server: "https://cluster-2-control-plane:6443"
