apiVersion: v1
kind: Secret
metadata:
  name: cluster-1-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "cluster-1"
  server: "https://cluster-1-control-plane:6443"
